### ISSUE TITLE
Add a tutorial.

### ISSUE THREAD

**Issue by YoannDupont** [YoannDupont/SEM#3]
## Need

First time users can be left wondering what to do with SEM.
There needs to be some turnkey solution so they can try at least the most basic SEM functionalities.

## Requirements

The tutorial should contain how to:
1. annotate raw text.
2. annotate CoNLL text.
3. output HTML and CoNLL data.

Files:
- A plain text file: use non regression corpora?
- A CoNLL (tabular) file: use non regression corpora?
- either instruction on how to change a configuration file or a specific configuration file to handle CoNLL.
- Some file containing instructions and command line commands.

**Comment by dcsouthwick** [comment]
I would really like to use this! My experience:

1. git clone https://github.com/YoannDupont/SEM.git
2. cd SEM/ext; tar zxvf waipiti-1.5.0.tar.gz;make;make install
(copy an example from http://www.lattice.cnrs.fr/sites/itellier/SEM.html ) 
3. 'echo Tout nouvel organisme public national sera implanté hors d'Ile-de-France. > test.text'
4. echo
 ```
<?xml version="1.0" encoding="UTF-8"?>
<master>
    <pipeline>
        <segmentation />
        <enrich config="pos-lefff.xml" />
        <label model="resources/models/plain+lefff" />
        <clean_info to-keep="0,-1" />
        <label model="model_all" />
    </pipeline>
</master>
``` 
into config.xml

4. ./sem tagger config.xml test.text

5. ??? crash.
```
File "~/SEM/src/tagger.py", line 94, in tagger
    document_segmentation(document, pipeline[0].args["name"], log_level=options.log_level, log_file=options.log_file)
KeyError: 'name'
```

**Comment by YoannDupont** [comment]
Hello ! Thanks for using SEM !

This reference is not really up to date, I'm sorry! Could you try the following:

```
cd <SEM directory>
cd ./resources/models/fr/POS
tar -xvzf plain.lefff.tar.gz
cd <SEM directory>
mkdir ./output
./sem tagger ./resources/master/fr/pos-lefff.xml test.text -o ./output
```

Please tell me if it works better for you.

**Comment by dcsouthwick** [comment]
Hmm no luck here either, but I suspect my Wapiti install is to blame:
```
~/SEM$ ./sem tagger ./resources/master/fr/pos-lefff.xml test.text -o output/
INFO	2017-05-14 22:55:04,083	sem.tagger	tagger	Reading test.text
INFO	2017-05-14 22:55:04,084	sem.segmentation	document_segmentation	Getting tokeniser "fr"
INFO	2017-05-14 22:55:04,089	sem.segmentation	document_segmentation	segmented "test.text" in 1 sentences, 11 tokens
INFO	2017-05-14 22:55:04,090	sem.segmentation	document_segmentation	in 0:00:00.005918
INFO	2017-05-14 22:55:04,090	sem.enrich	document_enrich	loading ./resources/master/fr/../../enrich/fr/pos-lefff.xml
INFO	2017-05-14 22:55:04,320	sem.enrich	document_enrich	done in 0:00:00.230237
INFO	2017-05-14 22:55:04,373	sem.tagger	tagger	labeling POS with wapiti
Traceback (most recent call last):
  File "./sem", line 56, in <module>
    runpy.run_module(modules[operation], run_name="__main__", alter_sys=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/david/SEM/src/tagger.py", line 179, in <module>
    directory=args.output_directory)
  File "/Users/david/SEM/src/tagger.py", line 120, in tagger
    wapiti.label_document(document, model, field, oenc)
  File "/Users/david/SEM/obj/wapiti.py", line 126, in label_document
    wapiti_process     = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

~/SEM$ wapiti --version
Wapiti v1.5.0
  Optimization mode:   sse2
~/SEM$ which wapiti 
/usr/local/bin/wapiti
```

**Comment by YoannDupont** [comment]
Apologies for the delay, I thought I answered you!

SEM only uses a local wapiti now, can you please check if you still have your wapiti executable in the folder SEM/ext/wapiti?

The error you have looks like SEM is trying to access to the wapiti executable, which does not seem to exists anymore.

**Comment by dcsouthwick** [comment]
Hi Yoann-

Yes, that was exactly the problem. I had installed wapiti, but SEM does not look at system $PATH for it :) Thanks for following up!

**Comment by YoannDupont** [comment]
Glad I could be of some help! Hope you will find SEM useful.

**Comment by dcsouthwick** [comment]
I pulled your recent changes - but it looks like something was switched around!
Commands that used to work now die with unhappy Wapiti
```
./sem tagger resources/master/fr/NER.xml ./non-regression/fr/in/segmentation.txt -o sem_output
INFO	2017-05-30 15:14:53,047	sem.tagger	tagger	Reading ./non-regression/fr/in/segmentation.txt
INFO	2017-05-30 15:14:53,047	sem.segmentation	document_segmentation	Getting tokeniser "fr"
INFO	2017-05-30 15:14:53,053	sem.segmentation	document_segmentation	segmented "segmentation.txt" in 11 sentences, 122 tokens
INFO	2017-05-30 15:14:53,053	sem.segmentation	document_segmentation	in 0:00:00.005945
INFO	2017-05-30 15:14:53,056	sem.enrich	document_enrich	done in 0:00:00.001104
INFO	2017-05-30 15:14:53,056	sem.tagger	tagger	labeling POS with wapiti
INFO	2017-05-30 15:14:53,561	sem.tagger	tagger	labeled in 0:00:00.003249
INFO	2017-05-30 15:14:53,561	sem.clean_info	document_clean	cleaning document
INFO	2017-05-30 15:14:53,562	sem.clean_info	document_clean	done in 0:00:00.000340
INFO	2017-05-30 15:14:54,542	sem.enrich	document_enrich	done in 0:00:00.003924
INFO	2017-05-30 15:14:54,542	sem.tagger	tagger	labeling NER with wapiti
ERROR	2017-05-30 15:14:55,132	sem.wapiti	label_document	* Load model
ERROR	2017-05-30 15:14:55,132	sem.wapiti	label_document	* Label sequences
ERROR	2017-05-30 15:14:55,132	sem.wapiti	label_document	error: missing tokens, cannot apply pattern
ERROR	2017-05-30 15:14:55,132	sem.wapiti	label_document	Wapiti exited with status 1
Traceback (most recent call last):
  File "/Users/david/SEM/obj/wapiti.py", line 141, in label_document
    raise RuntimeError("Wapiti exited with status %i" %wapiti_process.returncode)
RuntimeError: Wapiti exited with status 1
Traceback (most recent call last):
  File "./sem", line 56, in <module>
    runpy.run_module(modules[operation], run_name="__main__", alter_sys=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/david/SEM/src/tagger.py", line 218, in <module>
    force_format=args.output_format)
  File "/Users/david/SEM/src/tagger.py", line 135, in tagger
    wapiti.label_document(document, model, field, oenc, annotation_fields=fields)
  File "/Users/david/SEM/obj/wapiti.py", line 141, in label_document
    raise RuntimeError("Wapiti exited with status %i" %wapiti_process.returncode)
RuntimeError: Wapiti exited with status 1
```

**Comment by YoannDupont** [comment]
The NER model changed on the most recent commits. If it was extracted, you should remove the extracted file and relaunch SEM (you won't need to extract the model yourself: SEM will do it).

**Comment by YoannDupont** [comment]
Hello David,

Did you manage to make it work?

**Comment by dcsouthwick** [comment]
Hi Yoann,

After forcing update of my clone, yes your command works! It outputs in a tagged html export.  I see from your updated documentation that you've added a gui. I've successfully used this to achieve the historical output in previous versions (simply tagged text) but haven't yet had the time to figure the command line options. I'm interested in Named Entity extraction, so I've been simply parsing the annotated text sources. Perhaps it better to take a more direct approach from your wapiti labeling output. 

P.S. Trying to run the gui first with 'default' and then re-running on the same text but changing the output to 'text' reproduces a caught crash 'Error: NER'. Attached terminal output below. 


```
INFO	2017-06-17 23:32:04,262	sem.tagger	tagger	Reading /Users/david/semv2/test.txt
INFO	2017-06-17 23:32:04,262	sem.segmentation	document_segmentation	Getting tokeniser "fr"
INFO	2017-06-17 23:32:04,263	sem.segmentation	document_segmentation	segmented "test.txt" in 1 sentences, 11 tokens
INFO	2017-06-17 23:32:04,263	sem.segmentation	document_segmentation	in 0:00:00.000668
INFO	2017-06-17 23:32:05,342	sem.enrich	document_enrich	done in 0:00:00.001104
INFO	2017-06-17 23:32:05,342	sem.tagger	tagger	labeling POS with wapiti
INFO	2017-06-17 23:32:05,945	sem.tagger	tagger	labeled in 0:00:00.007851
INFO	2017-06-17 23:32:05,945	sem.clean_info	document_clean	cleaning document
INFO	2017-06-17 23:32:05,946	sem.clean_info	document_clean	done in 0:00:00.000267
INFO	2017-06-17 23:32:05,946	sem.tagger	tagger	labeling chunking with wapiti
INFO	2017-06-17 23:32:06,200	sem.tagger	tagger	labeled in 0:00:00.006641
INFO	2017-06-17 23:32:06,201	sem.clean_info	document_clean	cleaning document
INFO	2017-06-17 23:32:06,201	sem.clean_info	document_clean	done in 0:00:00.000120
INFO	2017-06-17 23:32:06,209	sem.exportation	export	using loaded exporter
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "/Users/david/semv2/src/gui.py", line 154, in launch_tagger
    tagger(masterfile, current_file, directory=output_dir, force_format=export_format)
  File "/Users/david/semv2/src/tagger.py", line 172, in tagger
    export(document, exporter, current_output, lang=lang, lang_style=lang_style, pos_column=poscol, chunk_column=chunkcol, ner_column=nercol, ienc=oenc, oenc=oenc, log_level=options.log_level, log_file=options.log_file)
  File "/Users/david/semv2/src/posttreatment/export.py", line 91, in export
    exporter.document_to_file(infile, couples, outfile, encoding=oenc)
  File "/Users/david/semv2/obj/exporters/exporter.py", line 105, in document_to_file
    O.write(self.document_to_unicode(document, couples, **kwargs))
  File "/Users/david/semv2/obj/exporters/text.py", line 35, in document_to_unicode
    return self.corpus_to_unicode(document.corpus.sentences, couples, **kwargs)
  File "/Users/david/semv2/obj/exporters/text.py", line 65, in corpus_to_unicode
    for annotation in get_chunks(sentence, lower["ner"]):
  File "/Users/david/semv2/obj/storage/annotation.py", line 108, in chunk_annotation_from_sentence
    tag  = element[column]
KeyError: 'NER'
```

**Comment by YoannDupont** [comment]
Hi David,

I pushed a fix for "text" exporter, it should work now.

It looks like you were using a "chunking" workflow. Be sure to click on "select workflow: NER.xml" each time you launch the GUI (it does not remember the configuration from one run to another).

**Comment by dcsouthwick** [comment]
Hi Yoann,

I'm back again with another round of feedback.
I'm trying to use your latest updates in command line (so that this might be used with other software) and am finding some rather inconsistent behavior.

`./sem tagger resources/master/fr/pos-lefff.xml test.txt -o output` works, but trying to add a flag for text output crashes. 
```
./sem tagger resources/master/fr/pos-lefff.xml test.txt -o output -f text
INFO	2017-08-21 18:35:43,313	sem.tagger	tagger	Reading test.txt
INFO	2017-08-21 18:35:43,313	sem.segmentation	document_segmentation	Getting tokeniser "fr"
INFO	2017-08-21 18:35:43,316	sem.segmentation	document_segmentation	segmented "test.txt" in 1 sentences, 11 tokens
INFO	2017-08-21 18:35:43,316	sem.segmentation	document_segmentation	in 0:00:00.003030
INFO	2017-08-21 18:35:44,500	sem.enrich	document_enrich	done in 0:00:00.001088
INFO	2017-08-21 18:35:44,500	sem.tagger	tagger	labeling POS with wapiti
INFO	2017-08-21 18:35:45,113	sem.tagger	tagger	labeled in 0:00:00.002687
INFO	2017-08-21 18:35:45,113	sem.clean_info	document_clean	cleaning document
INFO	2017-08-21 18:35:45,113	sem.clean_info	document_clean	done in 0:00:00.000373
INFO	2017-08-21 18:35:45,140	sem.exportation	export	using loaded exporter
Traceback (most recent call last):
  File "./sem", line 56, in <module>
    runpy.run_module(modules[operation], run_name="__main__", alter_sys=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/david/sem_2017/src/tagger.py", line 218, in <module>
    force_format=args.output_format)
  File "/Users/david/sem_2017/src/tagger.py", line 172, in tagger
    export(document, exporter, current_output, lang=lang, lang_style=lang_style, pos_column=poscol, chunk_column=chunkcol, ner_column=nercol, ienc=oenc, oenc=oenc, log_level=options.log_level, log_file=options.log_file)
  File "/Users/david/sem_2017/src/posttreatment/export.py", line 91, in export
    exporter.document_to_file(infile, couples, outfile, encoding=oenc)
  File "/Users/david/sem_2017/obj/exporters/exporter.py", line 105, in document_to_file
    O.write(self.document_to_unicode(document, couples, **kwargs))
  File "/Users/david/sem_2017/obj/exporters/text.py", line 35, in document_to_unicode
    return self.corpus_to_unicode(document.corpus.sentences, couples, **kwargs)
  File "/Users/david/sem_2017/obj/exporters/text.py", line 51, in corpus_to_unicode
    if "pos" in lower and corpus.has_key(lower["pos"]):
AttributeError: 'list' object has no attribute 'has_key'
```

This command used to work ( this can be replicated with 
``` 
git checkout 124788d10be603a6b05f5b1e4e623ee2d1528608
./sem tagger resources/master/fr/pos-lefff.xml test.txt -o output -f text
```

What's going on here?

**Comment by YoannDupont** [comment]
Hi David,

Seems like I messed up a little bit in text exporter. It should be working fine now.

**Comment by dcsouthwick** [comment]
Hi Yoann-

Thanks for your quick response. I can confirm that commit worked 👍 

Some features i've discovered:
 * Empty files crash wapiti ( is this expected?) 
 * Long lines without cr or linebreaks crash wapiti (is this expected?) 
    - for example, exporting a word document to UTF-8 (since SEM does not handle docx) sometimes produces lines of text hundreds of words long.

Hope this helps those that might also hit this limitation

**Comment by YoannDupont** [comment]
Hello David,

I would not exactly call these "features" :laughing: 

- empty files: this is to be expected. Wapiti does not expect to have nothing.
- long lines: Could you provide an example or SEM's log? I launched SEM on a single line file with 100k tokens and everything went well.

**Comment by YoannDupont** [comment]
Tutorial under construction. Please go to:

https://github.com/YoannDupont/SEM-tutorial

Since the tutorial has its own git, I'm closing this issue. Anything about the tutorial will now happen in its git.
